---
- name: create a vmware rhel template
  hosts: localhost
  gather_facts: False
  connection: local
  become: no
  vars_files: ../vaults/template.yml
  vars:
    template_force: yes #overwrite existing template with the same name
    export_ovf: no # export the template to export domain upon creation
    local_account_password: '{{ vault_local_account_password }}'
    local_administrator_password: '{{ vault_local_administrator_password }}'
    distro_name: rhel8 # this needs to be one of the standard values see 'os_short_names' var
    template_vm_name: rhel81-x64-v1
    template_vm_guest_id: rhel8_64Guest
    template_vm_root_disk_size: 10
    template_vm_memory: 4096
    iso_file_name: 'rhel-8.7-x86_64-dvd.iso' # name of the iso file

    vcenter_datacenter: 'SagelyDC' # name of the datacenter
    vcenter_cluster: 'HighPower' # name of the cluster
    vcenter_resource_pool: 'Demo' # name of resource pool if applicable
    vcenter_folder: '/SagelyDC/vm/Demo' # name of the folder to keep the template
    vcenter_datastore: 'SSD2TB' # name of the datastore where iso file resides

    template_vm_network_name: DPG-Sandbox
    template_vm_ip_address: 192.168.20.80
    template_vm_netmask: 255.255.240.0
    template_vm_gateway: 192.168.16.1
    template_vm_domain: demo.toal.ca
    template_vm_root_disk_datastore: 'SSD2TB'
    template_vm_dns_servers:
    - 192.168.16.1
    - 8.8.8.8
    instance_wait_connection_timeout: 900

  roles:
    - oatakan.rhel_vcenter_template
...
