---
- name: Deploy EDA Server
  hosts: eda_servers
  become: true
  gather_facts: false
  vars_files:
    - ../vaults/template.yml

  tasks:
    - name: Create the VM
      vmware_guest:
        datacenter: 'SagelyDC'
        folder: /vm/Demo
        resource_pool: Demo
        name: '{{ inventory_hostname }}'
        state: poweredon
        guest_id: rhel8_64Guest
        annotation: "EDA"
        disk:
          - size_gb: 40
            type: thin
            datastore: 'SSD2TB'
        networks:
          - name: DPG-Sandbox
            ip: '{{ ip }}'
            netmask: 255.255.240.0
            gateway: 192.168.16.1
            dns_servers:
              - 192.168.16.1
        hardware:
          memory_mb: 16384
          num_cpus: 8
        customization:
          dns_servers:
            - 192.168.16.1
          domain: sandbox.toal.ca
          hostname: '{{ inventory_hostname }}'
        template: 'rhel81-x64-v1'
        wait_for_ip_address: true
      delegate_to: localhost


    - name: Wait for host to be up
      ansible.builtin.wait_for_connection:

    - name: Gather facts
      ansible.builtin.gather_facts:

    - name: Use pip to install ansible-rulebook
      ansible.builtin.pip:
        name: "ansible-rulebook"
        state: present
