---
- name: Gitlab Configuration
  hosts: '{{ env }}'
  connection: local
  vars_files:
    - "../vaults/{{ env }}.yml"

  tasks:
    - name: Gitlab Users
      community.general.gitlab_user:
        api_token: '{{ gitlab_api_token }}'
        api_url: '{{ gitlab_api_url }}'
        validate_certs: false
        password: '{{ item.password }}'
        username: '{{ item.user }}'
        name: '{{ item.user }}'
        email: '{{ item.user }}@demo.toal.ca'
        access_level: 'owner'
        confirm: no
      loop: '{{ controller_user_accounts_prod }}'

    - name: Gitlab Groups
      community.general.gitlab_group:
        api_token: '{{ gitlab_api_token }}'
        api_url: '{{ gitlab_api_url }}'
        validate_certs: false
        name: '{{ item.name }}'
        description: '{{ item.description }}'
        auto_devops_enabled: false
        avatar_path: ""
        parent: ""
        project_creation_level: maintainer
        subgroup_creation_level: maintainer
        visibility: public
      loop: '{{ controller_organizations_prod }}'

    - name: Gitlab Group Membership
      community.general.gitlab_group_members:
        api_token: '{{ gitlab_api_token }}'
        api_url: '{{ gitlab_api_url }}'
        validate_certs: false
        gitlab_group: '{{ item.name }}'
        gitlab_user: '{{ controller_roles_prod | selectattr("organizations","contains",item.name) |map(attribute="user")}}'
        access_level: maintainer
      loop: '{{ controller_organizations_prod }}'

    - name: Create GitLab Projects
      community.general.gitlab_project:
        api_token: '{{ gitlab_api_token }}'
        api_url: '{{ gitlab_api_url }}'
        validate_certs: false
        name: '{{ item.name }}'
        group: '{{ item.organization }}'
        issues_enabled: false
        merge_method: rebase_merge
        initialize_with_readme: false
        state: present
        import_url: '{{ item.upstream_url }}'
        visibility: public
      loop: '{{ controller_projects_prod }}'

    - name: Create Dev and QA Branches
      community.general.gitlab_branch:
        api_token: '{{ gitlab_api_token }}'
        api_url: '{{ gitlab_api_url }}'
        validate_certs: false
        project: '{{ item[0].organization }}/{{ item[0].name|lower }}'
        branch: '{{ item[1] }}'
        ref_branch: 'main'
        state: present
      with_nested:
        - '{{ controller_projects_prod }}'
        - ['dev','qa']
...
