---
- block:
    - name: Get Available Content Libraries
      vmware.vmware_rest.content_locallibrary_info:
      register: library_info

    - name: Library ID
      ansible.builtin.set_fact:
        appliance_library_id: "{{ library_info.value | selectattr('name','eq', library_name) | map(attribute='id') | first }}"

    - name: Get Appliance Info
      vmware.vmware_rest.content_library_item_info:
        library_id: "{{ appliance_library_id }}"
      register: library_items

    - name: Appliance ID
      ansible.builtin.set_fact:
        appliance_id: "{{ library_items.value | selectattr('name','eq', appliance_name) | map(attribute='id') | first }}"

    - name: Get Library Item Info
      vmware.vmware_rest.content_library_item_info:
        library_item_id: "{{ appliance_id }}"
      register: library_item_info
  delegate_to: localhost