---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - add_host:
        hostname: template_vm
        ansible_host: '192.168.20.80'
        host_key_checking: false
        ansible_user: "ansible"
        ansible_password: "rhD3mo.905"
        ansible_port: "22"
        ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
    - setup:
      delegate_to: template_vm
      retries: 10
      connection: ssh
